### ISSUE TITLE
issue 2

### ISSUE THREAD

**Issue by aozorahime** [rikyperdana/simrs#46]
Pada kasir rawat jalan (pasien baru) bukti pembayaran daftar pasien baru tidak masuk ke laporan pdf
![image](https://user-images.githubusercontent.com/38600745/91012627-94e32200-e610-11ea-8498-29cc4fe1c90b.png)

SOAP PERAWAT(OBSERVASI RAWAT INAP) TANGGAL UNDEFINED
![image](https://user-images.githubusercontent.com/38600745/91012649-a0364d80-e610-11ea-98a5-281d5f909fc7.png)

![image](https://user-images.githubusercontent.com/38600745/91012675-ac220f80-e610-11ea-97c3-8c381b76bfdc.png)

**Comment by rikyperdana** [comment]
Semua laporan diatas sudah diperbaiki, silahkan bantu cek lagi. Terimakasih
